services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb11.8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: ToDo
      MARIADB_ROOT_PASSWORD: ToDosecret
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 5

  todo-api:
    build: .
    container_name: todo-container
    ports:
      - "5555:5555"
    environment:
      DB_SERVER: mariadb
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ToDosecret
      DB_DATABASE: ToDo
      JWT_KEY: 555544FinPenGamerTodDenTodAye555544
      JWT_ISSUER: ToDo
      JWT_AUDIENCE: public
    depends_on:
      mariadb:
        condition: service_healthy
